import "./globals.css";
import { Quicksand } from "next/font/google";
import StoreProvider from "./store/storeProvider";

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-quicksand",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${quicksand.variable}  antialiased`}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
